# Generated by Django 3.2 on 2021-11-10 10:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='ForumTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('post_count', models.IntegerField(default=0, verbose_name='Колличество подтем')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Изоображение')),
                ('forumTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumtitle', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='ForumMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('post_count', models.IntegerField(default=0, verbose_name='Колличество сообщений')),
                ('forumTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumtop', verbose_name='Тема')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(forum.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Подтему',
                'verbose_name_plural': 'Подтемы',
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(max_length=240, verbose_name='Сообщение')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('forumMiddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forummiddle', verbose_name='Подтема')),
                ('user', models.ForeignKey(on_delete=models.SET(forum.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения форума',
            },
        ),
    ]
