# Generated by Django 3.2 on 2021-12-11 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forummiddle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(forum.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='forumMiddle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forummiddle', verbose_name='Подтема'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(forum.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
