# Generated by Django 3.2 on 2021-12-23 14:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(max_length=1100, verbose_name='Сообщение')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения форума',
            },
        ),
        migrations.CreateModel(
            name='ForumTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='ForumTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('post_count', models.IntegerField(default=0, verbose_name='Колличество подтем')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Изоображение')),
                ('forumTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumTitle', to='forum.forumtitle', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='ForumMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('post_count', models.IntegerField(default=0, verbose_name='Колличество сообщений')),
                ('forumTop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumtop', to='forum.forumtop', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Подтему',
                'verbose_name_plural': 'Подтемы',
            },
        ),
    ]
